name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Python
        run: |
          # Lint only Python sources; tolerate long lines to reduce churn
          flake8 --max-line-length=120 --extend-ignore=E203,E266,E501,W503 . || true


